edunet/urls.py
from django.urls import path

from . import views

app_name = 'edunet'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('help/', views.HelpView.as_view(), name='help'),
    path('help/technical-report', views.pdf_view, name='tech_report'),
    path('contributors', views.ContributorView.as_view(), name='contributors'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('departments/', views.DepartmentListView.as_view(), name='departments'),
    path('<slug:department_slug>/', views.course_list, name='course_list'),
    path('<slug:department_slug>/<slug:course_slug>/', views.course_detail, name='course_detail'),
    path('<slug:department_slug>/<slug:course_slug>/tree-form/', views.tk_form, name='tk_form'),
    path('<slug:department_slug>/<slug:course_slug>/<int:transcript_num>-tree/', views.tk_view, name='tk_view'), # pylint: disable=line-too-long
    path('<slug:department_slug>/<slug:course_slug>/<int:transcript_num>-puzzle/', views.pz_view, name='pz_view'), # pylint: disable=line-too-long
]

edunet_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('edunet/', include('edunet.urls')),
    path('admin/', admin.site.urls),
]

edunet/models.py
'''
Contains the models neccesary to run the edunet website.

Models:
    Department
    Course
    Tree_of_Knowledge

'''
from django.db import models
from autoslug import AutoSlugField

class Department(models.Model):
    '''Class model used for the departments within the Yale website.'''
    department_name = models.CharField(max_length=50)
    department_abbreviation = models.CharField(max_length=10)
    department_slug = AutoSlugField(
        populate_from='department_name',
        unique=True, editable=True,
    )

    def __str__(self):
        return self.department_name

class Course(models.Model):
    '''Class model used for the courses within the Yale website.'''
    course_name = models.CharField(max_length=150)
    course_number = models.CharField(max_length=25)
    course_season = models.CharField(max_length=25)
    course_url = models.URLField(max_length=150)
    course_description = models.TextField(max_length=1000)
    course_structure = models.TextField(max_length=500)
    course_slug = AutoSlugField(
        populate_from='course_name',
        unique=True,
        editable=True,
        max_length=150,
    )

    def __str__(self):
        return self.course_name

class TreeOfKnowledge(models.Model):
    '''Class model used for the Tree of Knowledges generated by the course_processor.'''
    course = models.ForeignKey(Course, on_delete=models.CASCADE) # pylint: disable=line-too-long
    transcript_num = models.IntegerField()
    tree_of_knowledge = models.TextField()

    def __str__(self):
        return self.tree_of_knowledge

class PuzzleOfKnowledge(models.Model):
    '''Class model used for the Puzzle of Knowledge generated by the course_processir.'''
    course = models.ForeignKey(Course, on_delete=models.CASCADE) # pylint: disable=line-too-long
    transcript_num = models.IntegerField()
    puzzle_of_knowledge = models.TextField()

    def __str__(self):
        return self.course.course_number + ' Puzzle'

edunet/forms.py
'''
Contains the forms for the EduNet website.
'''
from django import forms

error_messages = {'ValueError': 'Value must be less then ten.'}

class TKForm(forms.Form):
    '''Class used to display the form that gets tree transcripts.'''
    np = forms.IntegerField(label='Nouns per Paragraph', max_value=10)
    nl = forms.IntegerField(label='Nouns per Lecture', max_value=10)
    t = forms.IntegerField(label='Transcript')

edunet/views.py
'''
Contains all the views for the edunet website.

CLASSES:
    IndexView(generic.TemplateView)
    HelpView(generic.TemplateView)
    SearchResultsView(generic.ListView)
    DepartmentListView(generic.ListView)
    SignUpView(generic.CreateView)
    ContributorView(generic.TemplateView)

FUNCTIONS:
    courseList(request, department_slug)
        returns rendering of a template with a list of courses
        for a particular department
    course_detail(request, department_slug, course_slug)
        returns rendering of a template with course details
    tk_form(request, department_slug, course_slug)
        returns rendering of a template with a form to request a
        specific tree of knowledge
    tk_view(request, department_slug, course_slug)
        returns rendering of a template with tree of knowledge
    pz_view(request, department_slug, course_Slug)
        returns rendering of a template with puzzle of knowledge

'''
from django.shortcuts import render
from django.views import generic
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import FileResponse, Http404

from hitcount.models import HitCount
from hitcount.views import HitCountMixin

from .utils import utils
from .forms import TKForm
from .models import Department, Course, TreeOfKnowledge

class HelpView(generic.TemplateView):
    '''Class used to display the student help page.'''
    template_name = 'edunet/help.html'

class SignUpView(generic.CreateView):
    '''Class allows for a user to signup for EduNet.'''
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'edunet/signup.html'

class IndexView(generic.TemplateView):
    '''Class used to display the index page.'''
    template_name = 'edunet/index.html'

class ContributorView(generic.TemplateView):
    '''Class used to display contributors page.'''
    template_name = 'edunet/contributors.html'

class SearchResultsView(generic.ListView): # pylint: disable=too-many-ancestors
    '''Class used to display the page that contains the search results.'''
    template_name = 'edunet/search_results.html'
    model = Course

    def get_queryset(self):
        '''Function takes itself and returns a filtered object list based on the users search.'''
        query = self.request.GET.get('search_query')
        object_list = Course.objects.filter(
            Q(course_name__icontains=query) | Q(course_number__icontains=query)
        )
        return object_list

class DepartmentListView(generic.ListView): # pylint: disable=too-many-ancestors
    '''Class used to display the list ov available departments.'''
    template_name = 'edunet/department.html'
    context_object_name = 'departments'
    model = Department
    slug_url_kwarg = 'department_slug' # slug to reference for URL (value after ':')
    slug_field = 'slug' # match slug used in model
    queryset = Department.objects.order_by('department_name')

def course_list(request, department_slug):
    '''Function used to display a list of courses based on a particular department.'''

    # Filter courses if course number contains department abbreviation
    objects_unfiltered = Course.objects.filter(
        Q(course_number__icontains=Department.objects.get(department_slug=department_slug).department_abbreviation) # pylint: disable=line-too-long
    )
    request.session.set_test_cookie() # test cookies
    context = {
        'department': Department.objects.get(department_slug=department_slug),
        'courses': objects_unfiltered.order_by('course_name'),
    }
    return render(request, 'edunet/course_list.html', context)

def course_detail(request, department_slug, course_slug):
    '''Function used to display a template that contains all the details of a course.'''

    # Filter out transcripts from other courses
    matching_courses = TreeOfKnowledge.objects.filter(
        course__course_name=Course.objects.get(course_slug=course_slug)
    )
    transcript_numbers = [tree.transcript_num for tree in matching_courses]
    # declared to pass empty dictionary into context to avoid error
    transcripts = {}
    if len(transcript_numbers) != 0:
        titles = utils.get_lecture_titles(Course.objects.get(course_slug=course_slug))
        transcripts = utils.create_dict_from_two_list(transcript_numbers, titles)

    # Testing cookies
    if request.session.test_cookie_worked():
        request.session.delete_test_cookie()
        print('Cookie worked.')
    else:
        print('Cookie did not work.')

    hit_count = HitCount.objects.get_for_object(Course.objects.get(course_slug=course_slug))
    hit_count_reponse = HitCountMixin.hit_count(request, hit_count)
    print(hit_count_reponse)

    context = {
        'transcripts': transcripts,
        'course': Course.objects.get(course_slug=course_slug),
        'department': Department.objects.get(department_slug=department_slug),
    }
    return render(request, 'edunet/course_detail.html', context)

@login_required
def tk_form(request, department_slug, course_slug):
    '''
    Function used to display a form for a specific course that allows the user to input desired
    constraints for the retrieval of a Tree of Knowledge for that course.
    '''
    error_message = ''
    if request.method == 'GET':
        form = TKForm(request.GET)
        if form.is_valid():
            kpp = form.cleaned_data['np'] # keywords per paragraph
            kpl = form.cleaned_data['nl'] # keywords per lecture
            transcript_num = form.cleaned_data['t'] # transcript number
            if utils.validate_transcript_num(transcript_num, Course.objects.get(course_slug=course_slug)) is True: # pylint: disable=line-too-long
                # get tree based on keywords and transcript
                tree = utils.retrieve_tree_of_knowledge(
                    kpp, kpl, transcript_num, Course.objects.get(course_slug=course_slug)
                )
                return tk_view(request, department_slug, course_slug, tree)
            transcript_total_num = utils.get_transcript_num(Course.objects.get(course_slug=course_slug)) # pylint: disable=line-too-long
            error_message = 'The transcript does not exist. There is only ' + str(transcript_total_num) + ' transcripts.' # pylint: disable=line-too-long
    form = TKForm()
    context = {
        'form': form,
        'course': Course.objects.get(course_slug=course_slug),
        'department': Department.objects.get(department_slug=department_slug),
        'error_message': error_message,
    }
    return render(request, 'edunet/tk_form.html', context)

@login_required
def tk_view(request, department_slug, course_slug, tree=None, transcript_num=None):
    '''
    Function takes a request, department_slug, course_slug, and tree of knowledge with user
    entered keyword numbers in order to render a template with the specific
    courses Tree of Knowledge.
    '''
    if transcript_num is not None:
        tree = utils.get_tree_of_knowledge(Course.objects.get(course_slug=course_slug), transcript_num) # pylint: disable=line-too-long
    context = {
        'paragraph_num': len(tree['Paragraphs']),
        'lecture_title': tree['Lecture Title'],
        'lecture_kw': {'Lecture Keywords': tree['Lecture Keywords']},
        'paragraph_kw': {'Paragraphs': tree['Paragraphs']},
        'course': Course.objects.get(course_slug=course_slug),
        'department': Department.objects.get(department_slug=department_slug)
    }
    return render(request, 'edunet/tk.html', context)

@login_required
def pz_view(request, department_slug, course_slug, transcript_num):
    '''
    Function takes a request, department_slug, course_slug, and puzzle of knowledge with user
    entered keyword numbers in order to render a template with the specific
    courses Puzzle of Knowledge.
    '''
    if transcript_num < 10:
        transcript_num = '0' + str(transcript_num)
    puzzle = utils.get_course_number_link_format(Course.objects.get(course_slug=course_slug)) + '_' + str(transcript_num) # pylint: disable=line-too-long
    lecture_title = utils.get_puzzle_title(
        Course.objects.get(course_slug=course_slug), transcript_num
    )
    context = {
        'lecture_title': lecture_title,
        'puzzle': puzzle,
        'course': Course.objects.get(course_slug=course_slug),
        'department': Department.objects.get(department_slug=department_slug)
    }
    return render(request, 'edunet/pz.html', context)

"""
@login_required
def course_processor(request, department_slug, course_slug):
    '''
    Takes a request, department slug, and course slug and returns an html page
    signifying that the process was successful.
    '''
    utils.process_courses(Course.objects.get(course_slug=course_slug))
    context = {
        'department': Department.objects.get(department_slug=department_slug),
        'course': Course.objects.get(course_slug=course_slug),
    }
    return render(request, 'edunet/course_processor.html', context)

# for course detail template
<!--<p><a href="{% url 'edunet:course_processor' department.department_slug course.course_slug %}">Click here to process courses, this may take a minute.</a></p>-->
# for url.py
path('<slug:department_slug>/<slug:course_slug>/course-processor', views.course_processor, name='course_processor'), # pylint: disable=line-too-long
"""

def pdf_view(request):
    '''Return a pdf for the user to view.'''
    try:
        return FileResponse(
            open('edunet/static/edunet/technical-report.pdf', 'rb'), content_type='application/pdf'
        )
    except FileNotFoundError:
        raise Http404()

edunet/templates/edunet/base.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="keywords" content="HTML, CSS, JavaScript">
        <meta name="description" content="Educational applications for students">
        {% block authors %}
            <meta name="author" content="Rian Boutin">
        {% endblock %}

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        
        <!-- Custom CSS -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'edunet/style.css' %}">
        <title>Edunet: {% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="{% url 'edunet:index' %}">EduNet</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'edunet:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'edunet:departments' %}">Departments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'edunet:help' %}">Help</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'edunet:contributors' %}">Contributors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">EduNet Features:</a>
                    </li>
                    {% block nav %}{% endblock %}
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:login' %}">Admin</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown01">
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                                <a class="dropdown-item" href="{% url 'password_reset' %}">Reset Password</a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                <form action="{% url 'edunet:search_results' %}" method="GET" class="form-inline my-2 my-lg-0">
                    <input name="search_query" class="form-control mr-sm-2" type="text" placeholder="Search Courses..." aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
                {% endif %}
            </div>
        </nav>

        <main role="main">

            {% block header %}{% endblock %}

            {% block body %}{% endblock %}

        </main>

        <footer class="container">
            <p>&copy;EduNet Company 2020</p>
        </footer>
    </body>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

edunet/templates/edunet/contributors.html
{% extends 'edunet/base.html' %}

{% block title %} Contributors {% endblock %}

{% block header %} <h2>EduNet would like to recognize its Contributors...</h2> {% endblock %}

{% block body %}
    <style>
        ul {
            list-style-type: none;
        }
    </style>

    <h6>Fairfield University</h6>
    <ul>
        <li><a href="mailto:rusu@fairfield.edu">Adrian Rusu</a></li>
        <li><a href="mailto:daintong@hotmail.com">Gary Dainton</a></li>
        <li><a href="mailto:rian.boutin@student.fairfield.edu">Rian Boutin</a></li>
    </ul>
    <h6>Yale University</h6>
    <ul>
        <li>Various professors for supplying their courses</li>
    </ul>
    <h6>Private</h6>
    <ul>
        <li><a href="mailto:becheru@gmail.com">Alex Becheru</a></li>
        <li><a href="mailto:soft.gandhi@gmail.com">Anurag Gandhi</a></li>
    </ul>

{% endblock %}

edunet/templates/edunet/course_detail.html
{% extends 'edunet/base.html' %}

{% load hitcount_tags %}

{% block title %} {{ course.course_number }} {% endblock %}

{% block nav %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'edunet:course_list' department.department_slug %}">{{ department.department_abbreviation }} Courses</a>
</li>
{% endblock %}

{% block header %}<h2>Course Detail View</h2>{% endblock %}

{% block body %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'edunet/tree-style.css' %}">

    {% load static %}
    <img src="{% static 'edunet/images/yale_logo.png' %}" alt="Yale Logo" width="15%">

    <h6>Department: {{ department.department_name }}</h6> 
    <h6>Course: {{ course.course_name }} {{ course.course_number }}</h6>

    <p>{{ course.course_description }}</p>
    <p><a href="{{ course.course_url }}">Click here to visit the course at the Yale website.</a></p>

    {% if user.is_authenticated %}
        {% if transcripts %}
            <h5>Processed lectures for this course.</h5>
            <ul class="myUL">
                {% for number, title in transcripts.items %}
                    <li><span class="box">Lecture: {{ number }} {{ title }}</span>
                        <ul class="nested">
                            <li><a href="{% url 'edunet:tk_view' department.department_slug course.course_slug number %}">Click to view Tree of Knowledge</a></li>
                            <li><a href="{% url 'edunet:pz_view' department.department_slug course.course_slug number %}">Click to view Puzzle of Knowledge</a></li>
                        </ul>
                    </li>
                {% endfor %}
            </ul>
            <p><a href="{% url 'edunet:tk_form' department.department_slug course.course_slug %}">Click here to submit a tree transcript form request with your desired keywords.</a></p>
        {% else %}
            <p>No processed lectures available</p>
        {% endif %}
    {% else %}
        <p>Please <a href="{% url 'edunet:signup' %}">signup</a> or <a href="{% url 'login' %}">login</a> to use the EduNet features.</p>
    {% endif %}

    <p>Visits: {% get_hit_count for course %}</p>

    <script>
        var toggler = document.getElementsByClassName("box");
        var i;
        
        for (i = 0; i < toggler.length; i++) {
          toggler[i].addEventListener("click", function() {
            this.parentElement.querySelector(".nested").classList.toggle("active");
            this.classList.toggle("check-box");
          });
        }
    </script>

{% endblock %}

edunet/templates/edunet/course_list.html
{% extends 'edunet/base.html' %}

{% block title %} {{ department.department_name }} Courses {% endblock %}

{% block header %} <h1>Course List View</h1> {% endblock %}

{% block body %}

    <h3>{{ department.department_name }}</h3>

    {% if courses %}
        <ul>
            {% for course in courses %}
                <li><a href="{% url 'edunet:course_detail' department.department_slug course.course_slug %}">{{ course.course_name }} {{ course.course_number }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no available course for this department.</p>
    {% endif %}

{% endblock %}

edunet/templates/edunet/course_processor.html
{% extends 'edunet/base.html' %}

{% block title %} Course Processor {% endblock %}

{% block nav %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'edunet:course_list' department.department_slug %}">{{ department.department_name }}</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'edunet:course_detail' department.department_slug course.course_slug %}">{{ course.course_number }}</a>
</li>
{% endblock %}

{% block header %} <h3>Course Processor View</h3> {% endblock %}

{% block body %}

    <p>
        {{ course.course_name }} has been sucessfully processed. 
        Click <a href="{% url 'edunet:course_detail' department.department_slug course.course_slug %}">here</a> 
        to return to the course detail page.
    </p>

{% endblock %}

edunet/templates/edunet/department.html
{% extends 'edunet/base.html' %}

{% block title %} Departments {% endblock %}

{% block header %} <h1>Department List View</h1> {% endblock %}

{% block body %}
            
    {% if departments %}
        <ul>
            {% for department in departments %}
                <li><a href="{% url 'edunet:course_list' department.department_slug %}">{{ department.department_name }} {{ department.department_abbreviation }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No departments available.</p>
    {% endif %}

{% endblock %}

edunet/templates/edunet/index.html
{% extends 'edunet/base.html' %}

{% block title %} Home {% endblock %}

{% block header %} 
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Welcome to the Educational Network</h1>
            {% if user.is_authenticated %}
                <p>Hey, {{ user.username }}, are you ready for enjoyable and efficient studying?</p>
            {% else %}
                <p>Login <a href="{% url 'login' %}">here.</a>&nbspNot a member? Signup <a href="{% url 'edunet:signup' %}">here.</a></p>
            {% endif %}
            <p><a class="btn btn-primary btn-lg" href="{% url 'edunet:help' %}" role="button">Learn more &raquo;</a></p>
        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4">
                <h2>Tree of Knowledge</h2>
                <p>The <i>Tree of Knowledge</i> consists of keywords extracted from a lecture. There are keywords extracted from the lecture as a whole and keywords extracted from each paragraph within the lecture transcript. The number of keywords can be chosen up to, but not exceeding ten.</p>
                <p><a class="btn btn-secondary" href="{% url 'edunet:help' %}" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Puzzle of Knowledge</h2>
                <p>The <i>Puzzle of Knowledge</i> allows for an interactive experience. The student must complete a puzzle with the pieces that are given. The pieces are keywords and the most important ones must be placed in the center. To complete the puzzle, the pieces must then be placed in an order that spirals out.</p>
                <p><a class="btn btn-secondary" href="{% url 'edunet:help' %}" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Contributors</h2>
                <p>EduNet would like to thank Fairfield University for developing and funding this project. We would also like to thank Yale University for supplying the online courses that are available on this site.</p>
                <p><a class="btn btn-secondary" href="{% url 'edunet:contributors' %}" role="button">View details &raquo;</a></p>
            </div>
        </div>

        <hr>

    </div> <!-- /container -->
{% endblock %}

edunet/templates/edunet/tk.html
{% extends 'edunet/base.html' %}

{% block title %} {{ course.course_number }} Tree {% endblock %}

{% block nav %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'edunet:course_list' department.department_slug %}">{{ department.department_name }}</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'edunet:course_detail' department.department_slug course.course_slug %}">{{ course.course_number }}</a>
</li>
{% endblock %}

{% block header %}
    <h2>Course: {{ course.course_name }} {{ course.course_number }}</h2>
    <h4>Lecture: {{ lecture_title }} Tree of Knowledge</h4>
{% endblock %}

{% block body %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'edunet/tree-style.css' %}">

    <p>A tree view represents a hierarchical view of information, where each item can have a number of subitems. The most important keyword begin on the top for the item list and left for the tree view.</p>
    <p>Click on the box(es) to open or close the tree branches.</p>
    <p>There is a total of {{ paragraph_num }} paragraphs for this transcript.</p>
    <p><Strong>Note:</Strong> If there is less keywords then you requested then the requested amount exceeds the total amount of keywords for that paragraph.</p>

    <ul class="myUL">
        {% for key, value in lecture_kw.items %}
        <li><span class="box"><strong>{{ key }}</strong></span>
            <ul class="nested">
                {% for word in value %}
                <li><span class="box">{{ word }}</span>
                    <ul class="nested">
                        <li><a href="http://www.google.com/search?q={{word}}&btnI">Click to view definition...</li></a>
                    </ul>
                </li>  
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>

    <ul class="myUL">
        {% for key, value in paragraph_kw.items %}
        <li><span class="box"><strong>{{ key }}</strong></span>
            <ul class="nested">
                {% for k, v in value.items %}
                <li><span class="box"><strong>{{ k }}</strong></span>
                    <ul class="nested">
                        {% for w in v %}
                        <li><span class="box">{{ w }}</span>
                            <ul class="nested">
                                <li><a href="http://www.google.com/search?q={{w}}&btnI">Click to view definition...</li></a>
                            </ul>
                        </li>
                        {% endfor %}
                    </ul>
                </li>  
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
    
    <div class="container">
        <div class="tf-tree">
            <ul>
                {% for key, value in lecture_kw.items %}
                <li><span class="tf-nc">{{ key }}</span>
                    <ul>
                        {% for word in value %}
                        <li>
                            <a href="http://www.google.com/search?q={{word}}&btnI">
                                <span class="tf-nc">{{ word }}</span>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="container">
        <div class="tf-tree">
        <ul>
            {% for key, value in paragraph_kw.items %}
            <li><span class="tf-nc">{{ key }}</span>
            <ul>
                {% for k, v in value.items %}
                <li><span class="tf-nc">{{ k }}</span>
                <ul>
                    {% for w in v %}
                    <li>
                        <a href="http://www.google.com/search?q={{w}}&btnI">
                            <span class="tf-nc">{{ w }}</span>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
                </li>
                {% endfor %}
            </ul>
            </li>
            {% endfor %}
        </ul>
        </div>
    </div>

    <script>
        var toggler = document.getElementsByClassName("box");
        var i;
        
        for (i = 0; i < toggler.length; i++) {
          toggler[i].addEventListener("click", function() {
            this.parentElement.querySelector(".nested").classList.toggle("active");
            this.classList.toggle("check-box");
          });
        }
    </script>

{% endblock %}

edunet/templates/edunet/tk_form.html
{% extends 'edunet/base.html' %}

{% block title %} {{ course.course_number }} Tree Form {% endblock %}

{% block nav %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'edunet:course_list' department.department_slug %}">{{ department.department_name }}</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'edunet:course_detail' department.department_slug course.course_slug %}">{{ course.course_number }}</a>
</li>
{% endblock %}

{% block header %}
    <h6>Department: {{ department.department_name }}</h6> 
    <h6>Course: {{ course.course_name }}</h6>
{% endblock %}

{% block body %}
    <h6>Tree of Knowledge Form</h6>

    {{ error_message }}

    <form method="GET">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>

{% endblock %}